---
sync_rules:
  - name: dotfile_submodules
    from:
      - "piyoki/dot-qutebrowser"
      - "piyoki/dot-waybar"
      - "piyoki/dot-nvim"
      - "piyoki/dot-lf"
      - "piyoki/dot-lazygit"
      - "piyoki/dot-rofi"
      - "piyoki/dot-swaylock"
      - "piyoki/dot-swappy"
      - "piyoki/dot-tmux"
      - "piyoki/dot-fish"
      - "piyoki/dot-hypr"
      - "piyoki/dot-dunst"
      - "piyoki/dot-swaync"
      - "piyoki/dot-kitty"
      - "piyoki/dot-alacritty"
      - "piyoki/dot-foot"
    to: "piyoki/dotfiles.nix"
  - name: dotfiles_nixos
    from:
      - "piyoki/dotfiles.nix"
    to: "piyoki/nixos-config"
