---
sync_rules:
  - name: dotfile_submodules
    from:
      - "miooochi/dot-qutebrowser"
      - "miooochi/dot-waybar"
      - "miooochi/dot-nvim"
      - "miooochi/dot-lf"
      - "miooochi/dot-lazygit"
      - "miooochi/dot-rofi"
      - "miooochi/dot-swaylock"
      - "miooochi/dot-swappy"
      - "miooochi/dot-tmux"
      - "miooochi/dot-fish"
      - "miooochi/dot-hypr"
      - "miooochi/dot-dunst"
      - "miooochi/dot-swaync"
      - "miooochi/dot-kitty"
      - "miooochi/dot-alacritty"
      - "miooochi/dot-foot"
    to: "miooochi/dotfiles.nix"
  - name: dotfiles_nixos
    from:
      - "miooochi/dotfiles.nix"
    to: "miooochi/nixos-config"
