---
sync_rules:
  - name: dotfile_submodules
    from:
      - "yqlbu/dot-qutebrowser"
      - "yqlbu/dot-waybar"
      - "yqlbu/dot-nvim"
      - "yqlbu/dot-lf"
      - "yqlbu/dot-lazygit"
      - "yqlbu/dot-rofi"
      - "yqlbu/dot-swaylock"
      - "yqlbu/dot-swappy"
      - "yqlbu/dot-tmux"
      - "yqlbu/dot-fish"
      - "yqlbu/dot-hypr"
      - "yqlbu/dot-dunst"
      - "yqlbu/dot-swaync"
      - "yqlbu/dot-kitty"
      - "yqlbu/dot-alacritty"
    to: "yqlbu/dotfiles.nix"
  - name: dotfiles_nixos
    from:
      - "yqlbu/dotfiles.nix"
    to: "yqlbu/nixos-config"
